baseURL = "/"
languageCode = "zh-cn"
DefaultContentLanguage = "zh"
title = "horochx's blog"
theme = "terminal"
paginate = 10

[params]
  themeColor = "green"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true
  # favicon = "favicon.ico"
  showLastUpdated = true

[languages]

  [languages.zh]
    title = "horochx's blog"
    subtitle = "keep coding and learning"
    # copyright = '<span>© 2019 CC BY-SA 4.0</span>'
    copyright = '© 2019&nbsp;<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/" target="_blank">CC BY-SA 4.0</a>'
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.zh.params.logo]
      logoText = "horochx's blog"
      logoHomeLink = "/"

    [languages.zh.menu]

      [[languages.zh.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
