baseURL = "/"
languageCode = "zh-cn"
DefaultContentLanguage = "zh"
title = "horochx's blog"
theme = "terminal"
paginate =  10

googleAnalytics = "UA-140415078-1"

[params]
  themeColor = "green"
  showMenuItems = 4
  fullWidthTheme = false
  centerTheme = true
  # favicon = "favicon.ico"
  showLastUpdated = false

[languages]

  [languages.zh]
    title = "horochx's blog"
    subtitle = "keep coding and learning"
    copyright = "© 2017-2022 CC BY-SA 4.0"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.zh.params.logo]
      logoText = "horochx's blog"
      logoHomeLink = "/"

    [languages.zh.menu]

      [[languages.zh.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"

[markup]

  [markup.goldmark]

    [markup.goldmark.parser.attribute]
      block = true
      title = true
      
    [markup.goldmark.renderer]
      unsafe = true
